-- 1. Asegurar que la tabla existe
CREATE TABLE IF NOT EXISTS public.properties (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    title TEXT NOT NULL,
    category TEXT DEFAULT 'Residencial',
    price TEXT,
    location TEXT,
    description TEXT,
    long_description TEXT,
    image TEXT,
    whatsapp TEXT DEFAULT '526462394046'
);

-- 2. AGREGAR COLUMNAS FALTANTES (MIGRACIÓN)
-- Estas líneas agregan las columnas si no existen. Si ya existen, no pasa nada.
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'properties' AND column_name = 'gallery') THEN
        ALTER TABLE public.properties ADD COLUMN gallery TEXT[];
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'properties' AND column_name = 'features') THEN
        ALTER TABLE public.properties ADD COLUMN features TEXT[];
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'properties' AND column_name = 'amenities') THEN
        ALTER TABLE public.properties ADD COLUMN amenities TEXT[];
    END IF;
END $$;

-- 3. Habilitar seguridad (RLS)
ALTER TABLE public.properties ENABLE ROW LEVEL SECURITY;

-- 4. Crear política de lectura pública (si no existe)
DROP POLICY IF EXISTS "Allow public read access" ON public.properties;
CREATE POLICY "Allow public read access" ON public.properties FOR SELECT USING (true);

-- 5. Crear política de inserción/edición (Temporalmente abierta para facilitar tus pruebas)
-- ¡OJO! En producción deberías restringir esto, pero para que no tengas problemas al probar ahora:
DROP POLICY IF EXISTS "Allow full access to everyone" ON public.properties;
CREATE POLICY "Allow full access to everyone" ON public.properties FOR ALL USING (true);
